# Generated by Django 3.2.12 on 2023-01-05 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV_Website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip_address', models.CharField(max_length=40)),
                ('user_hostname', models.CharField(max_length=100)),
                ('user_agent', models.CharField(max_length=200)),
                ('tracked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
