# Generated by Django 3.2.12 on 2023-01-08 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV_Website', '0002_tracker'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formresult',
            old_name='email',
            new_name='email_sender',
        ),
        migrations.AddField(
            model_name='tracker',
            name='user_server',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
