# Generated by Django 3.2.12 on 2023-01-10 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CV_Website', '0005_blog'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='PDF',
        ),
    ]
