# Generated by Django 3.2.12 on 2023-01-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV_Website', '0007_auto_20230111_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='link',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image_portfolio',
            field=models.ImageField(blank=True, default='', null=True, upload_to='img/portfolio/'),
        ),
    ]
