# Generated by Django 3.2.12 on 2023-01-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV_Website', '0008_auto_20230111_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='user_hostname',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
