# Generated by Django 3.2.12 on 2023-01-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV_Website', '0009_alter_tracker_user_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='user_port',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
