# Generated by Django 3.2.12 on 2023-01-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CV_Website', '0011_alter_about_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='user_agent',
            field=models.CharField(max_length=1048),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='user_hostname',
            field=models.CharField(max_length=1048, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='user_port',
            field=models.CharField(max_length=1048, null=True),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='user_server',
            field=models.CharField(max_length=1048, null=True),
        ),
    ]
